/* ====================================================
 *   Setup lambda pour live-coder avec SuperCollider           
 *      Raphaël Forment, novembre / décembre 2021
 * ====================================================
 * 
 * Ce fichier fournit une configuration "par défaut". Certaines valeurs devront
 * être configurées pour correspondre à la machine que vous utilisez. N'hésitez
 * pas à allouer beaucoup de mémoire même si vous ne l'utilisez pas.
 *
 */
